/*
 * error_codes.h
 *
 *  Created on: Dec 2, 2019
 *      Author: asus
 */

#ifndef EXT_LIB_SRC_ERROR_CODES_H_
#define EXT_LIB_SRC_ERROR_CODES_H_

typedef enum
{
	ERR_NO_ERROR =0,

	ERR_PARAM_NULL_PTR_DETECT  		= 0x500,
	ERR_LOCK_FAIL,
	ERR_MALLOC_FAIL,
	ERR_PARAM_ERROR,

	//Serial Port errors	0x1001
	ERR_SER_PORT_INIT_FAIL				= 0x1001,



	//SPI Errors			0x2001

	//I2C errors			0x3001

	//CAN Errors			0x4001

	//FREERTOS errors		0x5001

	ERR_FRTOS_INIT_FAIL                =   0x5001,
	ERR_RTOS_SEM_INIT_FAIL=1,
	ERR_RTOS_MTX_INIT_FAIL,
	ERR_RTOS_QUE_INIT_FAIL,
	ERR_RTOS_EVT_INIT_FAIL,
	ERR_RTOS_TMR_INIT_FAIL,
	ERR_RTOS_TMR_START_FAIL,
	ERR_RTOS_TASK_INIT_FAIL,

	//Quectel Open CPU NUcleus RTOS errors	0x6001

	ERR_QL_OCPU_SEM_INIT_FAIL			=	0x6001,
	ERR_QL_OCPU_MTX_INIT_FAIL,
	ERR_QL_OCPU_QUE_INIT_FAIL,
	ERR_QL_OCPU_EVT_INIT_FAIL,
	ERR_QL_OCPU_TMR_REG_FAIL,
	ERR_QL_OCPU_TMR_START_FAIL,
	ERR_QL_OCPU_TASK_INIT_FAIL,


	/*	//SMS errors
	ERR_SMS_READ_FAIL 					=	0x10001,
	ERR_SMS_INVALID_INDEX,
	ERR_SMS_SEND_FAIL,
	ERR_SMS_DELETE_FAIL,*/

	//Sys CFG Error
	ERR_CFG_DATA_CORRUPT				=	0x11001,
	ERR_CFG_DATA_INVALID,
	ERR_CFG_DATA_WRITE_FAIL,
	ERR_CFG_DATA_READ_FAIL,
	ERR_INIT_FAIL,

	//PCOM module error
	ERR_PCOM_UART_NOT_SUPPORTED		=   0x12001,
	ERR_PCOM_UART_DMA_INIT_FAIL,
	ERR_PCOM_UART_DMA_STOP_FAIL,
	ERR_PCOM_PORT_INIT_FAIL,
	ERR_PCOM_PORT_DEINIT_FAIL,
	ERR_PCOM_SPI_NOT_SUPPORTED,
	ERR_PCOM_SPI_INIT_FAIL,
	ERR_PCOM_SPI_DEINIT_FAIL,
	ERR_PCOM_SPI_NOT_INITILIZED,
	ERR_PCOM_SPI_DMA_TXRX_FAIL,
	ERR_PCOM_SPI_DMA_TXRX_TIMEOUT,
	ERR_PCOM_SPI_DMA_TX_FAIL,
	ERR_PCOM_SPI_DMA_TX_TIMEOUT,
	ERR_PCOM_SPI_DMA_RX_FAIL,
	ERR_PCOM_SPI_DMA_RX_TIMEOUT,
	ERR_PCOM_I2C_NOT_SUPPORTED,
	ERR_PCOM_I2C_DMA_MEM_RD_FAIL,
	ERR_PCOM_I2C_DMA_MEM_WR_FAIL,
	ERR_PCOM_I2C_DMA_MEM_RD_TOUT,
	ERR_PCOM_I2C_DMA_MEM_WR_TOUT,
	ERR_PCOM_ADC_CONV_TIMEOUT,
	ERR_PCOM_ADC_START_DMA_FAIL,
	ERR_PCOM_MALLOC_FAIL,

	ERR_PCOM_QSPI_NOT_SUPPORTED,
	ERR_PCOM_QSPI_INIT_FAIL,
	ERR_PCOM_QSPI_DEINIT_FAIL,
	ERR_PCOM_QSPI_NOT_INITILIZED,
	ERR_PCOM_QSPI_DMA_TX_FAIL,
	ERR_PCOM_QSPI_DMA_TX_TIMEOUT,
	ERR_PCOM_QSPI_DMA_RX_FAIL,
	ERR_PCOM_QSPI_DMA_RX_TIMEOUT,
	ERR_PCOM_QSPI_IT_CMD_FAIL,
	ERR_PCOM_QSPI_IT_CMD_TIMEOUT,
	ERR_PCOM_QSPI_STRUCT_FAIL,
	ERR_PCOM_QSPI_IT_AUTOPOL_FAIL,




	ERR_VDN_CAN_SEND_FAIL			= 0x160001,

	ERR_FILE_BLOCK_READ_FAILED		=	 0x170001
}EErrorCode;

#endif /* EXT_LIB_SRC_ERROR_CODES_H_ */
